# Model configurations for xBD pipeline

# Localization model (SpaceNet) configuration
localization:
  model:
    name: "unet"
    backbone: "resnet50"
    pretrained: true
    in_channels: 3
    num_classes: 1
    activation: "sigmoid"
  
  training:
    batch_size: 8
    num_epochs: 100
    learning_rate: 0.0001
    weight_decay: 0.0001
    optimizer: "adam"
    scheduler: "cosine"
    warmup_epochs: 5
    
  data:
    image_size: [1024, 1024]
    train_val_split: 0.2
    augmentation:
      horizontal_flip: true
      vertical_flip: true
      rotate: true
      rotate_limit: 45
      brightness_contrast: true
      brightness_limit: 0.2
      contrast_limit: 0.2

# Damage classification model configuration
damage_classification:
  model:
    name: "resnet50"
    pretrained: true
    num_classes: 4  # no-damage, minor, major, destroyed
    dropout: 0.5
  
  training:
    batch_size: 32
    num_epochs: 50
    learning_rate: 0.001
    weight_decay: 0.0001
    optimizer: "adam"
    scheduler: "cosine"
    warmup_epochs: 3
    
  data:
    image_size: [224, 224]
    train_val_split: 0.2
    augmentation:
      horizontal_flip: true
      vertical_flip: true
      rotate: true
      rotate_limit: 30
      brightness_contrast: true
      brightness_limit: 0.2
      contrast_limit: 0.2
      random_crop: true

# Logging and checkpointing
logging:
  tensorboard: true
  wandb: true
  wandb_project: "xbd-pipeline"
  checkpoint_dir: "checkpoints"
  save_best_only: true
  monitor: "val_f1_score"
  mode: "max"
  save_frequency: 5  # epochs

# Inference settings
inference:
  batch_size: 16
  confidence_threshold: 0.5
  output_format: "geojson"  # or "csv"
  visualize: true
  save_overlays: true 