data:
  base_dir: "Data"
  train_dir: "train"
  test_dir: "test"
  image_dir: "images"
  label_dir: "labels"
  mask_dir: "masks"
  target_dir: "targets"
  image_size: [512, 512]
  batch_size: 4
  num_workers: 2

models:
  localization:
    checkpoint: "models/localization/checkpoint.pth"
    output_name: "localization_model.pth"
    architecture: "resnet50"
    pretrained: true
    learning_rate: 0.001
    weight_decay: 0.0001
    num_epochs: 1
    early_stopping_patience: 10

  damage:
    checkpoint: "models/damage/checkpoint.pth"
    output_name: "damage_model.pth"
    architecture: "resnet50"
    pretrained: true
    learning_rate: 0.001
    weight_decay: 0.0001
    num_epochs: 100
    early_stopping_patience: 10
    damage_levels:
      0:
        name: "no_damage"
        min_confidence: 0.7
      1:
        name: "minor_damage"
        min_confidence: 0.7
      2:
        name: "major_damage"
        min_confidence: 0.7
      3:
        name: "destroyed"
        min_confidence: 0.7

inference:
  threshold: 0.5
  batch_size: 16
  device: "cuda"  # or "cpu"
  save_debug: true
  debug_dir: "debug"
  output_format: "geojson"  # or "csv"
  min_confidence: 0.7

logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "pipeline.log" 